events {
    worker_connections 1024;
}

http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    server {
        # Nasloucháme POUZE na portu 443 se zapnutým SSL [cite: 120]
        listen 443 ssl;
        listen [::]:443 ssl;

        # Tvoje doména 
        server_name mmravec.42.fr;

        # Cesty k certifikátům, které jsme vygenerovali v Dockerfile
        ssl_certificate /etc/nginx/ssl/inception.crt;
        ssl_certificate_key /etc/nginx/ssl/inception.key;

        # Povolíme striktně pouze TLSv1.2 a TLSv1.3 
        ssl_protocols TLSv1.2 TLSv1.3;

        # Kde budou uloženy soubory webu (sem později namapujeme volume) [cite: 89, 90]
        root /var/www/html;
        index index.php index.html index.htm;

        location / {
            try_files $uri $uri/ =404;
        }

        # Přesměrování PHP požadavků do WordPress kontejneru na port 9000 
        location ~ \.php$ {
            fastcgi_split_path_info ^(.+\.php)(/.+)$;
            # NGINX bude hledat kontejner s názvem 'wordpress' v Docker síti
            fastcgi_pass wordpress:9000;
            fastcgi_index index.php;
            include fastcgi_params;
            fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
            fastcgi_param PATH_INFO $fastcgi_path_info;
        }
    }
}