# --- docker-compose-bonus.yml ---
services:
  # --- DATABASE ---
  mariadb:
    build: requirements/mariadb
    container_name: mariadb
    restart: always
    env_file: .env
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - inception

  # --- WORDPRESS APP ---
  wordpress:
    build: requirements/wordpress
    container_name: wordpress
    restart: always
    env_file: .env
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - inception
    depends_on:
      - mariadb

  # --- WEB SERVER (NGINX) ---
  nginx:
    build: requirements/nginx
    container_name: nginx
    restart: always
    env_file: .env
    ports:
      - "443:443"
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - inception
    depends_on:
      - wordpress
      - lighttpd

  # --- BONUS: ADMINER ---
  adminer:
    build: requirements/bonus/adminer
    container_name: adminer
    restart: always
    ports:
      - "8080:8080"
    networks:
      - inception
    depends_on:
      - mariadb

  # --- BONUS: LIGHTTPD ---
  lighttpd:
    build: requirements/bonus/static_web
    container_name: lighttpd
    restart: always
    expose:
      - "3000"
    networks:
      - inception

# --- NETWORK DEFINITION ---
networks:
  inception:
    driver: bridge

# --- VOLUMES DEFINITION ---
volumes:
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/mmravec/data/mariadb
  wordpress_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/mmravec/data/wordpress