# 1. Port where the server listens for incoming requests (from NGINX)
server.port          = 3000

# 2. Physical location of your copied index.html
server.document-root = "/var/www/html"

# 3. User and group under which the process should run (security standard)
server.username      = "lighttpd"
server.groupname     = "lighttpd"

# 4. Default file to load when someone accesses the root directory
index-file.names     = ( "index.html" )

# 5. Mime-types: So the browser knows .html is a webpage and not a text file to download
mimetype.assign      = (
  ".html" => "text/html", 
  ".txt"  => "text/plain",
  ".css"  => "text/css",
  ".js"   => "application/x-javascript",
  ".jpg"  => "image/jpeg",
  ".jpeg" => "image/jpeg",
  ".gif"  => "image/gif",
  ".png"  => "image/png" 
)